export const MAX_SCROLLABLE_HEIGHT = 250;
export const SPACING_S = 5;
export const SPACING_M = 10;
export const SPACING_L = 15;
export const SPACING_XL = 25;
export const TRANSITION_FAST = 200;
export const TRANSITION_NORMAL = 500;
export const TRANSITION_SLOW = 1000;

export const TOP_BAR_HEIGHT = 32;
export const STATUS_PANEL_WIDTH = 600;
export const STATUS_PANEL_HEIGHT_MULTIPLIER = 0.9;

export const NOTIFICATION_TOAST_MAX_TITLE_WIDTH_CHARS = 15;
export const NOTIFICATION_TOAST_MAX_SUMMARY_WIDTH_CHARS = 15;
export const NOTIFICATION_TOAST_MAX_BODY_WIDTH_CHARS = 34;
export const NOTIFICATION_TOAST_MIN_CONTENT_LINES = 2;
export const NOTIFICATION_TOAST_MAX_CONTENT_LINES = 3;

export const TASK_BAR_MIN_WIDTH_MULTIPLIER = 0.1;
